apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.connection.database }}
  POSTGRES_USER: {{ .Values.connection.username }}
  POSTGRES_PASSWORD: {{ .Values.connection.password }}
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-metadata
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}